// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var CookieParser = require("cookie-parser");

function make(secret, _) {
  if (secret) {
    return CookieParser(secret[0]);
  } else {
    return CookieParser();
  }
}

exports.make = make;
/* cookie-parser Not a pure module */
